apiVersion: v1
kind: Service
metadata:
  name: lab3-frontend-service
spec:
  type: NodePort
  selector:
    app: frontend-app-lab3
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: http