apiVersion: v1
kind: Service
metadata:
  name: frontend-app-lab2-service
spec:
  type: NodePort
  selector:
    app: frontend-app-lab2
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001